### ISSUE TITLE
More advanced linkrot checking

### ISSUE THREAD

**Issue by le717** [le717/webring#2]
> x failed pings over x period of time (reasonable should be determined)
 > without a successful ping
> successful ping should reset all counters
> if it exceeds threshold it should then become definitely rotted
> we don't want it to go rotted because cloudflare went down, basically

Wayback Machine API docs: https://archive.org/help/wayback_api.php

**Comment by ZAdamMac** [comment]
This is a better idea than the original two-strikes.

Could always make the failure count and the holdover period configurable via envvars.

**Comment by le717** [comment]
Would a "definitely rotted" link then be checked against the web archive api and updated to point to it instead? What if it cannot be found on the web archive (an increasingly rare happening but it still happens)?

**Comment by ZAdamMac** [comment]
That's a good edge case. I think if no archive is available, the link should remain the same but either the title or description should be tagged.

And that's definitely a case where that alert email or whatever should trigger, because it probably needs pruned.

**Comment by noghiri** [comment]
i set the variables to X because we should probably tweak - and different rings may want different settings. I'm also really not sure what our defaults should be - maybe the time period should be a week?

**Comment by ZAdamMac** [comment]
A week sounds like a sane baseline. We don't want to trip over things like provider outages or routing hiccups, and we're also not doing uptime monitoring for the people who are part of the ring.

Should things in the "maybe" rotstate be tested more frequently though? Daily, maybe? And should we have an update endpoint/method to set something back to "not rotted" if the admin checks and find the thing is fine?

It could work with the existing update method; I'll make sure that the admin wrapper I'm writing makes that a simple command.

**Comment by noghiri** [comment]
Manual-run-test as well as manual-set for admin is a good idea - even just for testing, we'll want to be able to force an up-test. stuff in maybe should definitely be tested daily (or maybe once every couple hours - might need configuration capability?)

**Comment by le717** [comment]
Since the update command is a PATCH request, you can literally just pass `{"rotted": "yes" | "no" | "maybe"}` and it'll change the flag. Logic to reset any counters based on the input can be added as needed.

Endpoints to check all links and a single link for rottenness already exists.

How would we want to record the check results? I'm assuming in the db, but I'm not thinking too clearly right now and I can't generate a schema for it.

**Comment by ZAdamMac** [comment]
Do we need the precise results of the check itself to be stored /anywhere/, or is it enough to just store the suspect state `rotted`?

**Comment by le717** [comment]
I'm referring to the number of times a link has passed the ping check so the scheduled check can decide how to set the `rotted` flag.

I think I just figured it out anyway. It'll be a new table (`rotted_links`) that's just

uuid | times_failed
---- | -----
uuid | int

A record is only added when the check first fails and updated on repeated checks. If it passes, the record is deleted.

**Comment by le717** [comment]
Implemented in #3. Feel free to take a look.
